#!/bin/sh

DAEMON="majestic"
PIDFILE="/var/run/$DAEMON.pid"

DAEMON_ARGS="-s"

# shellcheck source=/dev/null
[ -r "/etc/default/$DAEMON" ] && . "/etc/default/$DAEMON"

load_majestic() {
	printf 'Starting %s: ' "$DAEMON"
	[ -f /usr/bin/$DAEMON ] || echo -en "DISABLED, "
	# shellcheck disable=SC2086 # we need the word splitting
	start-stop-daemon -b -m -S -q -p "$PIDFILE" -x "/usr/bin/$DAEMON" \
		-- $DAEMON_ARGS
	status=$?
	if [ "$status" -eq 0 ]; then
		echo "OK"
	else
		echo "FAIL"
	fi
	return "$status"
}

# The daemon does not create a pidfile, and use "-m" to instruct start-stop-daemon to create one.
start() {
	#logger -s -p daemon.info -t novatek "Check MAC for Novatek devices"
	#if [ "$(fw_printenv -n ethaddr)" = "D0:22:12:88:88:88" ]; then
	#	logger -s -p daemon.info -t novatek "The eth0 interface has a lousy MAC, let's try to change it.."
	#else
	#	logger -s -p daemon.info -t novatek "The eth0 interface has a correct MAC - $(fw_printenv -n ethaddr)"
	#fi
	#
	logger -s -p daemon.info -t novatek "Loading of kernel modules and initialization of the video system has started"
	export TZ=$(cat /etc/TZ)
	load_novatek -i
	#
	load_majestic
}

stop() {
	printf 'Stopping %s: ' "$DAEMON"
	[ -f /usr/bin/$DAEMON ] || echo -en "DISABLED, "
	start-stop-daemon -K -s 9 -q -p "$PIDFILE"
	status=$?
	if [ "$status" -eq 0 ]; then
		rm -f "$PIDFILE"
		echo "OK"
	else
		echo "FAIL"
	fi
	return "$status"
}

restart() {
	stop
	sleep 1
	start
}

reload() {
	load_majestic
}

case "$1" in
	start|stop|restart|reload)
		"$1";;
	*)
		echo "Usage: $0 {start|stop|restart|reload}"
		exit 1
esac
