#!/bin/sh
#
# OpenIPC.org | 2024
#

PATH_MODULE=/lib/modules/5.10.61/sigmastar
PATH_SENSOR=${PATH_MODULE}/sensor
SENSOR=$(fw_printenv -n sensor)

detect_sensor() {
	insmod ${PATH_SENSOR}/sensor_config.ko
	if [ -e /dev/srcfg ]; then
		echo srcfg 0 1 0 0 0 0 > /dev/srcfg
		rmmod sensor_config
	fi
	SENSOR=$(ipcinfo -s)
	fw_setenv sensor ${SENSOR}
}

set_sensor() {
	case ${SENSOR} in
		sc401ai|sc501ai)
			insmod ${PATH_SENSOR}/sensor_${SENSOR}_mipi.ko chmap=1
			;;
		*)
			echo -e "\n\e[1;31mUNSUPPORTED sensor - ${SENSOR}\e[0m\n" | logger -s -t OpenIPC
			;;
	esac
}

insert_ko() {
	insmod ${PATH_MODULE}/mi_common.ko g_ModParamPath=${PATH_MODULE}/param.json config_json_path=/${PATH_MODULE}/config.json
	insmod ${PATH_MODULE}/mi_sys.ko
	insmod ${PATH_MODULE}/mi_vif.ko
	insmod ${PATH_MODULE}/mi_sensor.ko
	insmod ${PATH_MODULE}/mi_isp.ko
	insmod ${PATH_MODULE}/mi_rgn.ko
	insmod ${PATH_MODULE}/mi_scl.ko
	insmod ${PATH_MODULE}/mi_vcodec.ko drv_codec40_common.fw_load_path=/etc/firmware/chagall.bin
	insmod ${PATH_MODULE}/mi_venc.ko

	echo isproot /etc/firmware > /dev/ispmid
}

if [ ! -e /sys/module/mhal ]; then
	insert_ko
fi

if [ -z ${SENSOR} ]; then
	echo -e "\n\e[1;33mAutodetect sensor\e[0m\n" | logger -s -t OpenIPC
	detect_sensor
fi

if [ -z ${SENSOR} ]; then
	echo -e "\n\e[1;31mSensor parameter MISSING\e[0m\n" | logger -s -t OpenIPC
	exit 1
else
	echo -e "\n\e[1;32mSensor assigned - ${SENSOR}\e[0m\n" | logger -s -t OpenIPC
	if [ -e /sys/module/sensor* ]; then
		rmmod $(ls -d /sys/module/sensor* | cut -d/ -f4)
	fi
	set_sensor
fi

exit 0
