#!/bin/sh
#
# OpenIPC.org | 2024
#

MODULE=/lib/modules/5.10.61/sigmastar
SENSOR=$(fw_printenv -n sensor)

detect_sensor() {
	insmod $MODULE/sensor_config.ko
	if [ -e /dev/srcfg ]; then
		echo srcfg 0 1 0 0 0 0 > /dev/srcfg
		rmmod sensor_config
	fi
	SENSOR=$(ipcinfo -s)
	fw_setenv sensor "$SENSOR"
}

set_sensor() {
	case $SENSOR in
		gc4653|imx335|imx415|os04a10|sc4336p|sc401ai|sc501ai|sc830ai|sc850sl)
			insmod $MODULE/sensor_${SENSOR}_mipi.ko chmap=1
			;;
		*)
			echo -e "\n\e[1;31mUNSUPPORTED sensor - $SENSOR\e[0m\n" | logger -s -t OpenIPC
			;;
	esac
}

insert_ko() {
	insmod $MODULE/mi.ko drv_codec40_common.fw_load_path=/etc/firmware/chagall.bin
	echo isproot /etc/firmware > /dev/ispmid
}

if [ ! -e /sys/module/mi_common ]; then
	insert_ko
fi

if [ -z "$1" ] || [ -z "$SENSOR" ]; then
	echo -e "\n\e[1;33mAutodetect sensor\e[0m\n" | logger -s -t OpenIPC
	detect_sensor
fi

if [ -z "$SENSOR" ]; then
	echo -e "\n\e[1;31mSensor parameter MISSING\e[0m\n" | logger -s -t OpenIPC
	exit 1
fi

DRIVER=$(ls /sys/module | grep $SENSOR)
if [ -n "$DRIVER" ]; then
	rmmod $DRIVER
fi

echo -e "\n\e[1;32mSensor assigned - $SENSOR\e[0m\n" | logger -s -t OpenIPC
set_sensor

exit 0
