include $(BR2_EXTERNAL_HISILICON_PATH)/linux/linux-ext-hisi_patcher.mk
include $(BR2_EXTERNAL_HISILICON_PATH)/package/hisi_patcher/hisi_patcher.mk
include $(BR2_EXTERNAL_HISILICON_PATH)/package/aura-httpd/aura-httpd.mk
include $(BR2_EXTERNAL_HISILICON_PATH)/package/gdbserver-lite/gdbserver-lite.mk
include $(BR2_EXTERNAL_HISILICON_PATH)/package/fwprintenv-ng/fwprintenv-ng.mk
include $(BR2_EXTERNAL_HISILICON_PATH)/package/hisi_gpio/hisi_gpio.mk
include $(BR2_EXTERNAL_HISILICON_PATH)/package/hisilicon-osdrv4/hisilicon-osdrv4.mk
include $(BR2_EXTERNAL_HISILICON_PATH)/package/ipctool/ipctool.mk
include $(BR2_EXTERNAL_HISILICON_PATH)/package/libevent-mini/libevent-mini.mk
include $(BR2_EXTERNAL_HISILICON_PATH)/package/libhvt/libhv.mk
include $(BR2_EXTERNAL_HISILICON_PATH)/package/libsrt/libsrt.mk
include $(BR2_EXTERNAL_HISILICON_PATH)/package/majestic/majestic.mk
include $(BR2_EXTERNAL_HISILICON_PATH)/package/node-exporter/node-exporter.mk
include $(BR2_EXTERNAL_HISILICON_PATH)/package/vtund-lite/vtund-lite.mk
include $(BR2_EXTERNAL_HISILICON_PATH)/package/yaml-cli/yaml-cli.mk
