include $(BR2_EXTERNAL_HISILICON_PATH)/linux/linux-ext-hisi_patcher.mk
include $(BR2_EXTERNAL_HISILICON_PATH)/package/aws-producer/aws-producer.mk
include $(BR2_EXTERNAL_HISILICON_PATH)/package/aws-webrtc/aws-webrtc.mk
include $(BR2_EXTERNAL_HISILICON_PATH)/package/hisi_patcher/hisi_patcher.mk
include $(BR2_EXTERNAL_HISILICON_PATH)/package/aura-httpd/aura-httpd.mk
include $(BR2_EXTERNAL_HISILICON_PATH)/package/baresip-openipc/baresip-openipc.mk
include $(BR2_EXTERNAL_HISILICON_PATH)/package/dropbear-openipc/dropbear-openipc.mk
include $(BR2_EXTERNAL_HISILICON_PATH)/package/f2fs-tools-openipc/f2fs-tools-openipc.mk
include $(BR2_EXTERNAL_HISILICON_PATH)/package/fdk-aac-openipc/fdk-aac-openipc.mk
include $(BR2_EXTERNAL_HISILICON_PATH)/package/fwprintenv-openipc/fwprintenv-openipc.mk
include $(BR2_EXTERNAL_HISILICON_PATH)/package/gdbserver-lite/gdbserver-lite.mk
include $(BR2_EXTERNAL_HISILICON_PATH)/package/hisi_gpio/hisi_gpio.mk
include $(BR2_EXTERNAL_HISILICON_PATH)/package/hisilicon-opensdk/hisilicon-opensdk.mk
include $(BR2_EXTERNAL_HISILICON_PATH)/package/hisilicon-osdrv-hi3516av100/hisilicon-osdrv-hi3516av100.mk
include $(BR2_EXTERNAL_HISILICON_PATH)/package/hisilicon-osdrv-hi3516cv100/hisilicon-osdrv-hi3516cv100.mk
include $(BR2_EXTERNAL_HISILICON_PATH)/package/hisilicon-osdrv-hi3516cv200/hisilicon-osdrv-hi3516cv200.mk
include $(BR2_EXTERNAL_HISILICON_PATH)/package/hisilicon-osdrv-hi3516cv300/hisilicon-osdrv-hi3516cv300.mk
include $(BR2_EXTERNAL_HISILICON_PATH)/package/hisilicon-osdrv-hi3516cv500/hisilicon-osdrv-hi3516cv500.mk
include $(BR2_EXTERNAL_HISILICON_PATH)/package/hisilicon-osdrv-hi3516ev300/hisilicon-osdrv-hi3516ev300.mk
include $(BR2_EXTERNAL_HISILICON_PATH)/package/hisilicon-osdrv-hi3519v101/hisilicon-osdrv-hi3519v101.mk
include $(BR2_EXTERNAL_HISILICON_PATH)/package/i2c-telemetry/i2c-telemetry.mk
include $(BR2_EXTERNAL_HISILICON_PATH)/package/ipctool/ipctool.mk
include $(BR2_EXTERNAL_HISILICON_PATH)/package/json-c-openipc/json-c-openipc.mk
include $(BR2_EXTERNAL_HISILICON_PATH)/package/lame-openipc/lame-openipc.mk
include $(BR2_EXTERNAL_HISILICON_PATH)/package/libcurl-openipc/libcurl-openipc.mk
include $(BR2_EXTERNAL_HISILICON_PATH)/package/libevent-openipc/libevent-openipc.mk
include $(BR2_EXTERNAL_HISILICON_PATH)/package/libhv-openipc/libhv-openipc.mk
include $(BR2_EXTERNAL_HISILICON_PATH)/package/libogg-openipc/libogg-openipc.mk
include $(BR2_EXTERNAL_HISILICON_PATH)/package/libre-openipc/libre-openipc.mk
include $(BR2_EXTERNAL_HISILICON_PATH)/package/librem-openipc/librem-openipc.mk
include $(BR2_EXTERNAL_HISILICON_PATH)/package/libsrt-openipc/libsrt-openipc.mk
include $(BR2_EXTERNAL_HISILICON_PATH)/package/libwebsockets-openipc/libwebsockets-openipc.mk
include $(BR2_EXTERNAL_HISILICON_PATH)/package/linux-firmware-openipc/linux-firmware-openipc.mk
include $(BR2_EXTERNAL_HISILICON_PATH)/package/majestic/majestic.mk
include $(BR2_EXTERNAL_HISILICON_PATH)/package/majestic-fonts/majestic-fonts.mk
include $(BR2_EXTERNAL_HISILICON_PATH)/package/mavlink-router/mavlink-router.mk
include $(BR2_EXTERNAL_HISILICON_PATH)/package/mbedtls-openipc/mbedtls-openipc.mk
include $(BR2_EXTERNAL_HISILICON_PATH)/package/microbe-web/microbe-web.mk
include $(BR2_EXTERNAL_HISILICON_PATH)/package/motors/motors.mk
include $(BR2_EXTERNAL_HISILICON_PATH)/package/mt7601u-ap-openipc/mt7601u-ap-openipc.mk
include $(BR2_EXTERNAL_HISILICON_PATH)/package/node-exporter/node-exporter.mk
include $(BR2_EXTERNAL_HISILICON_PATH)/package/opus-openipc/opus-openipc.mk
include $(BR2_EXTERNAL_HISILICON_PATH)/package/rtl8188eus-openipc/rtl8188eus-openipc.mk
include $(BR2_EXTERNAL_HISILICON_PATH)/package/rtw-hostapd/rtw-hostapd.mk
include $(BR2_EXTERNAL_HISILICON_PATH)/package/rtl8188fu-openipc/rtl8188fu-openipc.mk
include $(BR2_EXTERNAL_HISILICON_PATH)/package/rtl8812au-openipc/rtl8812au-openipc.mk
include $(BR2_EXTERNAL_HISILICON_PATH)/package/uacme-openipc/uacme-openipc.mk
include $(BR2_EXTERNAL_HISILICON_PATH)/package/uqmi-openipc/uqmi.mk
include $(BR2_EXTERNAL_HISILICON_PATH)/package/usrsctp/usrsctp.mk
include $(BR2_EXTERNAL_HISILICON_PATH)/package/vtund-openipc/vtund-openipc.mk
include $(BR2_EXTERNAL_HISILICON_PATH)/package/wifibroadcast/wifibroadcast.mk
include $(BR2_EXTERNAL_HISILICON_PATH)/package/xmdp/xmdp.mk
include $(BR2_EXTERNAL_HISILICON_PATH)/package/yaml-cli/yaml-cli.mk
include $(BR2_EXTERNAL_HISILICON_PATH)/package/zerotier-one/zerotier-one.mk
