#!/bin/sh

fstype=$(awk '$2=="/"{print $3}' /proc/mounts)
opts=$(awk '$2=="/"{print $4}' /proc/mounts)

case "$fstype" in
	nfs|nfs4|overlay)
		echo "Skipping root remount for $fstype root ($opts)"
		;;
	*)
		mount -o remount,rw /
		;;
esac

exit 0
