#!/bin/sh
#
# Customize environment for NFS boot
#

#!/bin/sh


# Setup NFS password
setup_root_passwd() {
    shadow_hash="$(awk -F: '$1=="root"{print $2}' /etc/shadow)"
    salt="$(printf '%s\n' "$shadow_hash" | cut -d'$' -f3)"
    test_hash="$(mkpasswd -m md5 -S "$salt" "@ROOTFS_PASSWD@")"
    if [ ! "$test_hash" = "$shadow_hash" ]; then
        echo "root:@ROOTFS_PASSWD@" | chpasswd 2>/dev/null
        echo "nfs-root: Updated root password."
    fi
}

setup_ssh_key() {
	if fw_printenv >/dev/null 2>&1; then
		if ! fw_printenv ssh_key >/dev/null 2>&1; then
			echo "nfs-root: Generating SSH key and saving to uboot env."
			tmp="$(mktemp -u /tmp/dropbearkey.XXXXXX)" || exit 1
			trap 'rm -f "$tmp"' EXIT

			dropbearkey -t ed25519 -f "$tmp" >/dev/null 2>&1 || exit 1
			SSH_KEY=$(cat "$tmp" | base64 -w 0)
			fw_setenv ssh_key $SSH_KEY || exit 1
		fi
		echo "nfs-root: Loading SSH key from uboot env."
		fw_printenv -n ssh_key 2>/dev/null | base64 -d > /etc/dropbear/dropbear_ed25519_host_key || exit 1
	else
		echo "nfs-root: fw_setenv inaccessible, SSH key will not be saved."
	fi
}

setup_dns_ntp() {
    IP=$(ip route | sed -n 's/^default via \([0-9.]*\) .*/\1/p')
    if [ -n "@NTP_SERVER@" ]; then
        echo "server @NTP_SERVER@ iburst" > /etc/ntp.conf
        echo "nfs-root: Using @NTP_SERVER@ for NTP."
    else
        echo "server ${IP} iburst" > /etc/ntp.conf
        echo "nfs-root: Using default gateway (${IP?}) for NTP."
    fi
    if [ -n "@DNS_SERVER@" ]; then
        echo "nameserver @DNS_SERVER@" > /etc/resolv.conf
        echo "nfs-root: Using @DNS_SERVER@ for DNS."
    else
        echo "nameserver ${IP}" > /etc/resolv.conf
        echo "nfs-root: Using default gateway (${IP?}) for DNS."
    fi
}

case "$1" in
    start)
        # Only run if booting from nfs root
        if grep -qw 'root=/dev/nfs' /proc/cmdline; then
            setup_root_passwd
            setup_dns_ntp
            setup_ssh_key
        fi
        ;;

    stop)
        ;;

    *)
        echo "Usage: $0 {start}"
        exit 1
        ;;
esac
