#!/bin/bash
# Tests for build_request.sh, the parser build-one.yml runs on a firmware
# explorer build request. The issue body is untrusted text, so the cases that
# matter most are the ones it must refuse.

set -u

SRC=${SRC:-.github/scripts/build_request.sh}
fail=0
ok()  { echo "ok   $*"; }
bad() { echo "FAIL $*"; fail=$((fail + 1)); }

[ -f "$SRC" ] || { echo "FAIL cannot find $SRC — run me from the repo root"; exit 1; }

SB=$(mktemp -d)
trap 'rm -rf "$SB"' EXIT

defconfig() { printf 'BR2_arm=y\nBR2_PACKAGE_WPA_SUPPLICANT=y\n' > "$SB/defconfig"; }

# The body exactly as the explorer composes it (kconfig.ts buildRequest).
cat > "$SB/good.md" <<'EOF'
<!-- Submitted from openipc.org/firmware-explorer. -->

## Summary
**Board**: `ssc337_ultimate`

## Defconfig fragment
```
# Generated by https://openipc.org/firmware-explorer
# Board: ssc337_ultimate
# Append these lines to your board defconfig, then re-run defconfig.

# BR2_PACKAGE_WPA_SUPPLICANT is not set
# BR2_PACKAGE_LIBNL is not set
# BR2_PACKAGE_WPA_SUPPLICANT is not set
```

Some text after the block.
```
# BR2_PACKAGE_MAJESTIC is not set
```
EOF

# 1. The explorer's own output applies, deduplicated, and nothing after the
#    first block is read.
defconfig
if sh "$SRC" apply "$SB/good.md" "$SB/defconfig" "$SB/syms" >/dev/null; then
	got=$(tr '\n' ' ' < "$SB/syms")
	[ "$got" = "BR2_PACKAGE_LIBNL BR2_PACKAGE_WPA_SUPPLICANT " ] && ok "explorer fragment parsed" || bad "explorer fragment parsed -- got '$got'"
	grep -qx '# BR2_PACKAGE_WPA_SUPPLICANT is not set' "$SB/defconfig" && ok "fragment appended to defconfig" || bad "fragment appended to defconfig"
	grep -q MAJESTIC "$SB/defconfig" && bad "a second fenced block was read" || ok "only the first block is read"
else
	bad "explorer fragment parsed -- apply failed"
fi

# 2. CRLF, as a body edited in a browser comes back.
defconfig
sed 's/$/\r/' "$SB/good.md" > "$SB/crlf.md"
sh "$SRC" apply "$SB/crlf.md" "$SB/defconfig" "$SB/syms" >/dev/null 2>&1 && [ "$(wc -l < "$SB/syms")" -eq 2 ] \
	&& ok "CRLF body parsed" || bad "CRLF body parsed"

# 3. Anything that is not '# BR2_X is not set' refuses the whole request and
#    leaves the defconfig alone.
refuse() {
	local desc=$1 line=$2
	defconfig
	printf '## Defconfig fragment\n```\n# BR2_PACKAGE_LIBNL is not set\n%s\n```\n' "$line" > "$SB/bad.md"
	if sh "$SRC" apply "$SB/bad.md" "$SB/defconfig" "$SB/syms" >/dev/null 2>&1; then
		bad "refuses $desc"
	elif [ "$(cat "$SB/defconfig")" != "$(printf 'BR2_arm=y\nBR2_PACKAGE_WPA_SUPPLICANT=y')" ]; then
		bad "refuses $desc -- but the defconfig was modified"
	else
		ok "refuses $desc"
	fi
}
refuse "an enabled symbol"          'BR2_PACKAGE_DROPBEAR=y'
refuse "a string assignment"        'BR2_TARGET_GENERIC_HOSTNAME="x"'
refuse "a command substitution"     '# BR2_$(reboot) is not set'
refuse "a lowercase symbol"         '# BR2_package_x is not set'
refuse "trailing text"              '# BR2_PACKAGE_X is not set; rm -rf /'
refuse "a non-BR2 symbol"           '# CONFIG_FOO is not set'

# 4. No block, or a block with only comments, is an error.
defconfig
printf '## Summary\nnothing here\n' > "$SB/none.md"
sh "$SRC" apply "$SB/none.md" "$SB/defconfig" "$SB/syms" >/dev/null 2>&1 && bad "refuses a body without a fragment" || ok "refuses a body without a fragment"
printf '## Defconfig fragment\n```\n# Generated by x\n```\n' > "$SB/empty.md"
sh "$SRC" apply "$SB/empty.md" "$SB/defconfig" "$SB/syms" >/dev/null 2>&1 && bad "refuses an empty fragment" || ok "refuses an empty fragment"

# 4b. Symbols the common fragment sets (build machinery: hostname, the host
#     U-Boot tools the repack needs) are dropped from the request, not applied;
#     a request made only of them is refused.
printf 'BR2_TARGET_GENERIC_HOSTNAME="x"\nBR2_PACKAGE_HOST_UBOOT_TOOLS=y\n' > "$SB/fragment"
defconfig
printf '## Defconfig fragment\n```\n# BR2_PACKAGE_HOST_UBOOT_TOOLS is not set\n# BR2_PACKAGE_LIBNL is not set\n```\n' > "$SB/prot.md"
out=$(sh "$SRC" apply "$SB/prot.md" "$SB/defconfig" "$SB/syms" "$SB/fragment" 2>&1)
if [ "$(cat "$SB/syms")" = "BR2_PACKAGE_LIBNL" ] && ! grep -q HOST_UBOOT "$SB/defconfig" && printf '%s' "$out" | grep -q "not switching off.*BR2_PACKAGE_HOST_UBOOT_TOOLS"; then
	ok "a symbol the common fragment sets is dropped, with a notice"
else
	bad "a symbol the common fragment sets is dropped, with a notice -- syms '$(cat "$SB/syms")', out '$out'"
fi
defconfig
printf '## Defconfig fragment\n```\n# BR2_PACKAGE_HOST_UBOOT_TOOLS is not set\n```\n' > "$SB/prot-only.md"
sh "$SRC" apply "$SB/prot-only.md" "$SB/defconfig" "$SB/syms" "$SB/fragment" >/dev/null 2>&1 \
	&& bad "refuses a request made only of protected symbols" || ok "refuses a request made only of protected symbols"

# 5. verify names the symbols a select turned back on, and only those.
printf 'BR2_PACKAGE_LIBNL\nBR2_PACKAGE_WPA_SUPPLICANT\n' > "$SB/syms"
printf 'BR2_PACKAGE_LIBNL=y\n# BR2_PACKAGE_WPA_SUPPLICANT is not set\n' > "$SB/.config"
got=$(sh "$SRC" verify "$SB/syms" "$SB/.config")
[ "$got" = "BR2_PACKAGE_LIBNL" ] && ok "verify reports a re-enabled symbol" || bad "verify reports a re-enabled symbol -- got '$got'"
printf '# BR2_PACKAGE_LIBNL is not set\n' > "$SB/.config"
got=$(sh "$SRC" verify "$SB/syms" "$SB/.config")
[ -z "$got" ] && ok "verify is silent when every symbol is off" || bad "verify is silent when every symbol is off -- got '$got'"
printf 'BR2_TARGET_GENERIC_HOSTNAME\n' > "$SB/syms"
printf 'BR2_TARGET_GENERIC_HOSTNAME="openipc"\n' > "$SB/.config"
got=$(sh "$SRC" verify "$SB/syms" "$SB/.config")
[ -z "$got" ] && ok "verify does not report a string value as a kept package" || bad "verify does not report a string value as a kept package -- got '$got'"
printf 'BR2_PACKAGE_X\n' > "$SB/syms"
printf 'BR2_PACKAGE_X=m\n' > "$SB/.config"
got=$(sh "$SRC" verify "$SB/syms" "$SB/.config")
[ "$got" = "BR2_PACKAGE_X" ] && ok "verify reports a tristate kept as a module" || bad "verify reports a tristate kept as a module -- got '$got'"

echo
[ $fail -eq 0 ] && echo "all build_request tests passed" || echo "$fail build_request test(s) failed"
exit $((fail > 0))
