include $(CONFIG)

all:
	@echo -e "\n# SDK" >> $(BR_CONF)
	@echo "BR2_TOOLCHAIN_BUILDROOT=y" >> $(BR_CONF)
	@echo "BR2_TOOLCHAIN_BUILDROOT_VENDOR=\"openipc\"" >> $(BR_CONF)
ifeq ($(BR2_TOOLCHAIN_EXTERNAL_CUSTOM_MUSL),y)
	@echo "BR2_TOOLCHAIN_BUILDROOT_MUSL=y" >> $(BR_CONF)
else ifeq ($(BR2_TOOLCHAIN_EXTERNAL_CUSTOM_GLIBC),y)
	@echo "BR2_TOOLCHAIN_BUILDROOT_GLIBC=y" >> $(BR_CONF)
else
	@echo "BR2_TOOLCHAIN_BUILDROOT_UCLIBC=y" >> $(BR_CONF)
endif
ifeq ($(BR2_TOOLCHAIN_EXTERNAL_LOCALE),y)
	@echo "BR2_TOOLCHAIN_BUILDROOT_LOCALE=y" >> $(BR_CONF)
endif
ifeq ($(BR2_TOOLCHAIN_EXTERNAL_CXX),y)
	@echo "BR2_TOOLCHAIN_BUILDROOT_CXX=y" >> $(BR_CONF)
endif
ifeq ($(BR2_TOOLCHAIN_EXTERNAL_OPENMP),y)
	@echo "BR2_GCC_ENABLE_OPENMP=y" >> $(BR_CONF)
endif
ifeq ($(BR2_TOOLCHAIN_EXTERNAL_HEADERS_5_10),y)
	@echo "BR2_PACKAGE_HOST_LINUX_HEADERS_CUSTOM_5_10=y" >> $(BR_CONF)
else ifeq ($(BR2_TOOLCHAIN_EXTERNAL_HEADERS_4_19),y)
	@echo "BR2_PACKAGE_HOST_LINUX_HEADERS_CUSTOM_4_19=y" >> $(BR_CONF)
else ifeq ($(BR2_TOOLCHAIN_EXTERNAL_HEADERS_4_9),y)
	@echo "BR2_PACKAGE_HOST_LINUX_HEADERS_CUSTOM_4_9=y" >> $(BR_CONF)
else ifeq ($(BR2_TOOLCHAIN_EXTERNAL_HEADERS_4_4),y)
	@echo "BR2_PACKAGE_HOST_LINUX_HEADERS_CUSTOM_4_4=y" >> $(BR_CONF)
else ifeq ($(BR2_TOOLCHAIN_EXTERNAL_HEADERS_3_18),y)
	@echo "BR2_PACKAGE_HOST_LINUX_HEADERS_CUSTOM_3_18=y" >> $(BR_CONF)
else ifeq ($(BR2_TOOLCHAIN_EXTERNAL_HEADERS_3_10),y)
	@echo "BR2_PACKAGE_HOST_LINUX_HEADERS_CUSTOM_3_10=y" >> $(BR_CONF)
else ifeq ($(BR2_TOOLCHAIN_EXTERNAL_HEADERS_3_4),y)
	@echo "BR2_PACKAGE_HOST_LINUX_HEADERS_CUSTOM_3_4=y" >> $(BR_CONF)
else ifeq ($(BR2_TOOLCHAIN_EXTERNAL_HEADERS_3_3),y)
	@echo "BR2_PACKAGE_HOST_LINUX_HEADERS_CUSTOM_3_3=y" >> $(BR_CONF)
else ifeq ($(BR2_TOOLCHAIN_EXTERNAL_HEADERS_3_0),y)
	@echo "BR2_PACKAGE_HOST_LINUX_HEADERS_CUSTOM_3_0=y" >> $(BR_CONF)
endif
	@echo "BR2_GCC_VERSION_13_X=y" >> $(BR_CONF)
	@echo "BR2_PACKAGE_HOST_GDB=y" >> $(BR_CONF)
	@echo "BR2_PACKAGE_AWS_WEBRTC=y" >> $(BR_CONF)
