#!/bin/sh

DAEMON="majestic"
PIDFILE="/var/run/$DAEMON.pid"
DAEMON_ARGS="-s"

debug_majestic() {
	[ -f /etc/coredump.conf ] && . /etc/coredump.conf
	if [ "$coredump_enabled" ]; then
		ulimit -c unlimited && echo "|/usr/sbin/sendcoredump.sh" > /proc/sys/kernel/core_pattern
	fi
}

load_majestic() {
	printf "Starting $DAEMON: "
	start-stop-daemon -b -S -m -q -p "$PIDFILE" -x "/usr/bin/$DAEMON" -- $DAEMON_ARGS
	status=$?
	if [ "$status" -eq 0 ]; then
		echo "OK"
	else
		echo "FAIL"
	fi
}

start() {
	logger -s -p daemon.info -t $(ipcinfo -v) "Loading video system has started..."
	export SENSOR=$(fw_printenv -n sensor)
	debug_majestic
	load_majestic
}

stop() {
	printf "Stopping $DAEMON: "
	start-stop-daemon -K -q -p "$PIDFILE"
	status=$?
	if [ "$status" -eq 0 ]; then
		rm -f "$PIDFILE"
		echo "OK"
	else
		echo "FAIL"
	fi
}

case "$1" in
	start|stop)
		"$1"
		;;

	restart)
		stop
		sleep 3
		load_majestic
		;;

	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
		;;
esac
