#!/bin/sh

DAEMON="/usr/bin/majestic"
DAEMON_ARGS="-s"

start() {
	echo -n "Starting $DAEMON: "
	start-stop-daemon -b -S -q -x "$DAEMON" -- $DAEMON_ARGS
	if [ $? -eq 0 ]; then
		echo "OK"
	else
		echo "FAIL (already running)"
	fi
}

stop() {
	echo -n "Stopping $DAEMON: "
	start-stop-daemon -K -q -x "$DAEMON"
	if [ $? -eq 0 ]; then
		echo "OK"
	else
		echo "FAIL"
	fi
}

case "$1" in
	start|stop)
		$1
		;;

	restart)
		stop
		sleep 3
		start
		;;

	reload)
		killall -1 "$DAEMON"
		;;

	*)
		echo "Usage: $0 {start|stop|restart|reload}"
		exit 1
		;;
esac
