#!/bin/sh
SOC=$(fw_printenv -n soc)

# HI3516EV300 CamHi
if [ "$SOC" = "hi3516ev300" ]; then
  devmem 0x100C0080 32 0x530
  echo 7 > /sys/class/gpio/export
  echo out > /sys/class/gpio/gpio7/direction
  echo 0 > /sys/class/gpio/gpio7/value
  sleep 1
  if lsusb | grep -q 7601; then
    modprobe mt7601usta
    exit 0
  fi
fi

# SSC338Q CamHi
if [ "$SOC" = "ssc338q" ]; then
  if lsusb | grep -q f72b; then
    modprobe 8733bu
    exit 0
  fi
fi

# SSC337DE Foscam
if [ "$SOC" = "ssc337de" ]; then
  echo 15 > /sys/class/gpio/export
  echo out > /sys/class/gpio/gpio15/direction
  echo 0 > /sys/class/gpio/gpio15/value
  sleep 1
  if lsusb | grep -q f179; then
    modprobe 8188fu
    exit 0
  fi
fi

# T21 BJS
if [ "$SOC" = "t21" ]; then
  echo 50 > /sys/class/gpio/export
  echo out > /sys/class/gpio/gpio50/direction
  echo 0 > /sys/class/gpio/gpio50/value
  sleep 1
  if lsusb | grep -q f179; then
    modprobe 8188fu
    exit 0
  fi
fi

exit 1
