#!/bin/sh

WIFI=$1

if [ "$WIFI" = "xm711" ]; then
    insmod /usr/lib/modules/dwc_common_port_lib.ko
    insmod /usr/lib/modules/dwc_otg.ko
    insmod /usr/lib/modules/wifi_pdn.ko value=96
    insmod /usr/lib/modules/compat.ko
    insmod /lib/modules/3.10.103+/kernel/net/wireless/cfg80211.ko
    insmod /usr/lib/modules/xm711.ko
fi

