#!/bin/sh

# Setting the TimeZone for all processes
/usr/sbin/timezone.sh
export TZ=$(cat /etc/TZ)

# Set the firmware creation time as the base system time
/bin/date -s @$(stat -t /etc/os-release | cut -d" " -f12)

# Start all init scripts in /etc/init.d
# executing them in numerical order.
for i in /etc/init.d/S??* ; do
	# Ignore dangling symlinks (if any).
	[ ! -f "$i" ] && continue

	case "$i" in
		*.sh)
			# Source shell script for speed.
			(
				trap - INT QUIT TSTP
				set start
				$i
			)
			;;

		*)
			# No sh extension, so fork subprocess.
			$i start
			;;
	esac
done
