#!/bin/sh

case "$1" in
	start)
		printf "Loading modules:"
		# load modules for detected devices
		# find /sys/ -name modalias -print0 | xargs -0 sort -u -z | xargs -0 modprobe -abq

		# load modules from /etc/modules
		[ -r /etc/modules ] || exit 0
		while read module args; do
			case "$module" in
				""|"#"*)
					continue
					;;
			esac

			# attempt to load modules
			modprobe ${module} ${args} > /dev/null
		done < /etc/modules
		;;
esac
