#!/bin/sh

DAEMON="rngd"
PIDFILE="/var/run/$DAEMON.pid"
RNGD_ARGS="-r /dev/urandom"

start() {
	printf "Starting $DAEMON: "
	start-stop-daemon -S -q -x "/usr/sbin/$DAEMON" -- $RNGD_ARGS
	if [ $? = 0 ]; then
		echo "OK"
	else
		echo "FAIL"
	fi
}

stop() {
	printf "Stopping $DAEMON: "
	start-stop-daemon -K -q -n "$DAEMON"
	if [ $? = 0 ]; then
		echo "OK"
	else
		echo "FAIL"
	fi
}

case "$1" in
	start|stop)
		"$1"
		;;

	restart|reload)
		stop
		sleep 1
		start
		;;

	*)
		echo "Usage: $0 {start|stop|restart|reload}"
		exit 1
		;;
esac
