#!/bin/sh

case "$1" in
	start)
		echo "Loading kernel modules..."
		[ -r /etc/modules ] || exit 0
		while read module args; do
			case "$module" in
				""|"#"*)
					continue
					;;
			esac
			modprobe "$module" "$args" > /dev/null
		done < /etc/modules
		;;

	stop)
		;;

	*)
		echo "Usage: $0 {start}"
		exit 1
		;;
esac
