#!/bin/sh

case "$1" in
	start)
		echo "Loading modules..."

		# load modules from /etc/modules
		[ -r /etc/modules ] || exit 0
		while read module args; do
			case "$module" in
				""|"#"*)
					continue
					;;
			esac

			# attempt to load modules
			modprobe ${module} ${args} > /dev/null
		done < /etc/modules
		;;
esac
