#!/bin/sh
#
# Start telnet server
#

TELNETD_ARGS="-F -p 4321 -l /bin/sh"
[ -r /etc/default/telnet ] && . /etc/default/telnet

start() {
      printf "Starting telnetd: "
      [ -f /usr/sbin/telnetd ] || (echo "IT IS MISSING" ; exit 1)
      start-stop-daemon -S -q -m -b -p /var/run/telnetd.pid \
			-x /usr/sbin/telnetd -- $TELNETD_ARGS
      [ $? = 0 ] && echo "OK (port 4321)" || echo "FAIL"
}

stop() {
	printf "Stopping telnetd: "
	[ -f /usr/sbin/telnetd ] || (echo "IT IS MISSING" ; exit 1)
	start-stop-daemon -K -q -p /var/run/telnetd.pid \
			  -x /usr/sbin/telnetd
	[ $? = 0 ] && echo "OK" || echo "FAIL"
}

case "$1" in
    start)
	start
	;;
    stop)
	stop
	;;
    restart|reload)
	stop
	start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
