#!/bin/sh

DAEMON="crond"
PIDFILE="/var/run/$DAEMON.pid"
CROND_ARGS="-f -c /etc/crontabs"

start() {
	printf "Starting $DAEMON: "
	start-stop-daemon -b -m -S -q -p "$PIDFILE" -x "/usr/sbin/$DAEMON" -- $CROND_ARGS
	if [ $? = 0 ]; then
		echo "OK"
	else
		echo "FAIL"
	fi
}

stop() {
	printf "Stopping $DAEMON: "
	start-stop-daemon -K -q -p "$PIDFILE"
	if [ $? = 0 ]; then
		rm -f "$PIDFILE"
		echo "OK"
	else
		echo "FAIL"
	fi
}

case "$1" in
	start|stop)
		"$1"
		;;

	restart|reload)
		stop
		sleep 1
		start
		;;

	*)
		echo "Usage: $0 {start|stop|restart|reload}"
		exit 1
		;;
esac
