#!/bin/sh

DAEMON="Telemetry_Transfer"
PIDFILE="/var/run/$DAEMON.pid"
COMMAND="socat UDP-RECV:2002 STDOUT | mcom -s 420000 /dev/ttyAMA0 | socat - udp-sendto:192.168.144.222:2001"

start() {
    echo -n "Starting $DAEMON: "
    start-stop-daemon -b -m -S -q -p "$PIDFILE" -x /bin/sh -- -c "$COMMAND"
    if [ $? -eq 0 ]; then
        echo "OK"
    else
        echo "FAIL"
    fi
}

stop() {
    echo -n "Stopping $DAEMON: "
    start-stop-daemon -K -q -p "$PIDFILE"
    if [ $? -eq 0 ]; then
        rm -f "$PIDFILE"
        echo "OK"
    else
        echo "FAIL"
    fi
}

restart() {
    stop
    sleep 3
    start
}


case "$1" in
    start)
        start
        ;;

    stop)
        stop
        ;;

    restart|reload)
        restart
        ;;

    *)
        echo "Usage: $0 {start|stop|restart|reload}"
        exit 1
        ;;
esac
