#!/bin/sh

# HI3516EV300 CamHi
if [ "$1" = "mt7601u-hi3516ev300-camhi" ]; then
	devmem 0x100C0080 32 0x530
	echo 7 > /sys/class/gpio/export
	echo out > /sys/class/gpio/gpio7/direction
	echo 0 > /sys/class/gpio/gpio7/value
	sleep 1
	modprobe mt7601u
	exit 0
fi

# SSC338Q CamHi
if [ "$1" = "8733bu-ssc338q-camhi" ]; then
	modprobe 8733bu
	exit 0
fi

# SSC337DE Foscam
if [ "$1" = "8188fu-ssc337de-foscam" ]; then
	echo 15 > /sys/class/gpio/export
	echo out > /sys/class/gpio/gpio15/direction
	echo 0 > /sys/class/gpio/gpio15/value
	sleep 1
	modprobe 8188fu
	exit 0
fi

# T21 BJS
if [ "$1" = "8188fu-t21-bjs" ]; then
	echo 50 > /sys/class/gpio/export
	echo out > /sys/class/gpio/gpio50/direction
	echo 0 > /sys/class/gpio/gpio50/value
	sleep 1
	modprobe 8188fu
	exit 0
fi

exit 1
