include $(BR2_EXTERNAL_FULLHAN_PATH)/linux/linux-ext-fullhan_patcher.mk
include $(BR2_EXTERNAL_FULLHAN_PATH)/package/fullhan_patcher/fullhan_patcher.mk
include $(BR2_EXTERNAL_FULLHAN_PATH)/package/aura-httpd/aura-httpd.mk
include $(BR2_EXTERNAL_FULLHAN_PATH)/package/fdk-aac-openipc/fdk-aac-openipc.mk
include $(BR2_EXTERNAL_FULLHAN_PATH)/package/fwprintenv-openipc/fwprintenv-openipc.mk
include $(BR2_EXTERNAL_FULLHAN_PATH)/package/ipctool/ipctool.mk
include $(BR2_EXTERNAL_FULLHAN_PATH)/package/lame-openipc/lame-openipc.mk
include $(BR2_EXTERNAL_FULLHAN_PATH)/package/libcurl-openipc/libcurl-openipc.mk
include $(BR2_EXTERNAL_FULLHAN_PATH)/package/libevent-openipc/libevent-openipc.mk
include $(BR2_EXTERNAL_FULLHAN_PATH)/package/libhv-openipc/libhv-openipc.mk
include $(BR2_EXTERNAL_FULLHAN_PATH)/package/libogg-openipc/libogg-openipc.mk
include $(BR2_EXTERNAL_FULLHAN_PATH)/package/libsrt-openipc/libsrt-openipc.mk
include $(BR2_EXTERNAL_FULLHAN_PATH)/package/majestic/majestic.mk
include $(BR2_EXTERNAL_FULLHAN_PATH)/package/mbedtls-openipc/mbedtls-openipc.mk
include $(BR2_EXTERNAL_FULLHAN_PATH)/package/motors/motors.mk
include $(BR2_EXTERNAL_FULLHAN_PATH)/package/node-exporter/node-exporter.mk
include $(BR2_EXTERNAL_FULLHAN_PATH)/package/opus-openipc/opus-openipc.mk
include $(BR2_EXTERNAL_FULLHAN_PATH)/package/uacme-openipc/uacme-openipc.mk
include $(BR2_EXTERNAL_FULLHAN_PATH)/package/vtund-openipc/vtund-openipc.mk
include $(BR2_EXTERNAL_FULLHAN_PATH)/package/yaml-cli/yaml-cli.mk