include $(BR2_EXTERNAL_FULLHAN_PATH)/linux/linux-ext-fullhan_patcher.mk
include $(BR2_EXTERNAL_FULLHAN_PATH)/package/fullhan_patcher/fullhan_patcher.mk
include $(BR2_EXTERNAL_FULLHAN_PATH)/package/aura-httpd/aura-httpd.mk
include $(BR2_EXTERNAL_FULLHAN_PATH)/package/fwprintenv-openipc/fwprintenv-openipc.mk
include $(BR2_EXTERNAL_FULLHAN_PATH)/package/ipctool/ipctool.mk
include $(BR2_EXTERNAL_FULLHAN_PATH)/package/libevent-openipc/libevent-openipc.mk
include $(BR2_EXTERNAL_FULLHAN_PATH)/package/libhv/libhv.mk
include $(BR2_EXTERNAL_FULLHAN_PATH)/package/libogg-openipc/libogg-openipc.mk
include $(BR2_EXTERNAL_FULLHAN_PATH)/package/libsrt/libsrt.mk
include $(BR2_EXTERNAL_FULLHAN_PATH)/package/majestic/majestic.mk
include $(BR2_EXTERNAL_FULLHAN_PATH)/package/mbedtls-openipc/mbedtls-openipc.mk
include $(BR2_EXTERNAL_FULLHAN_PATH)/package/node-exporter/node-exporter.mk
include $(BR2_EXTERNAL_FULLHAN_PATH)/package/opus-openipc/opus-openipc.mk
include $(BR2_EXTERNAL_FULLHAN_PATH)/package/vtund-openipc/vtund-openipc.mk
include $(BR2_EXTERNAL_FULLHAN_PATH)/package/yaml-cli/yaml-cli.mk