#!/bin/sh

WIFI=RTL8188

if [ "$WIFI" = "RTL8188" ]; then
	insmod /usr/lib/modules/dwc_common_port_lib.ko
	insmod /usr/lib/modules/dwc_otg.ko
	insmod /usr/lib/modules/wifi_pdn.ko value=96
	insmod /usr/lib/modules/cfg80211.ko
	insmod /usr/lib/modules/8188fu.ko
fi

