#!/bin/sh
#
# Start MAVlink Router
#

case "$1" in
  start)
      echo "Starting mavlink router daemon..."
      /usr/bin/mavlink-routerd &
    ;;
  stop)
    echo "Stopping mavlink router daemon..."
    kill -9 $(pidof mavlink-routerd)
    ;;
    *)
    echo "Usage: $0 {start|stop}"
    exit 1
esac
