#!/bin/sh

case "$1" in
	start)
		echo "Generating or updating /etc/vtx_info.yaml..."
		generate_vtx_info.sh
		;;

	stop)
		echo "Generating or updating /etc/vtx_info.yaml only done when starting..."
		
		;;

	*)
		echo "Usage: $0 {start|stop}"
		exit 1
		;;
esac
