#!/bin/sh

case "$1" in
	start)
		echo "Starting temperature check..."
		temp_monitor &>/dev/null &
		;;

	stop)
		echo "Stopping temperature check..."
		killall -q temp_monitor
		;;

	*)
		echo "Usage: $0 {start|stop}"
		exit 1
		;;
esac
