include $(BR2_EXTERNAL_XIONGMAI_PATH)/linux/linux-ext-xiongmai_patcher.mk
include $(BR2_EXTERNAL_XIONGMAI_PATH)/package/xiongmai_patcher/xiongmai_patcher.mk
include $(BR2_EXTERNAL_XIONGMAI_PATH)/package/aura-httpd/aura-httpd.mk
include $(BR2_EXTERNAL_XIONGMAI_PATH)/package/fwprintenv-openipc/fwprintenv-openipc.mk
include $(BR2_EXTERNAL_XIONGMAI_PATH)/package/ipctool/ipctool.mk
include $(BR2_EXTERNAL_XIONGMAI_PATH)/package/lame-openipc/lame-openipc.mk
include $(BR2_EXTERNAL_XIONGMAI_PATH)/package/libcurl-openipc/libcurl-openipc.mk
include $(BR2_EXTERNAL_XIONGMAI_PATH)/package/libevent-openipc/libevent-openipc.mk
include $(BR2_EXTERNAL_XIONGMAI_PATH)/package/libhv-openipc/libhv-openipc.mk
include $(BR2_EXTERNAL_XIONGMAI_PATH)/package/libogg-openipc/libogg-openipc.mk
include $(BR2_EXTERNAL_XIONGMAI_PATH)/package/libsrt-openipc/libsrt-openipc.mk
include $(BR2_EXTERNAL_XIONGMAI_PATH)/package/majestic-xm510/majestic-xm510.mk
include $(BR2_EXTERNAL_XIONGMAI_PATH)/package/majestic-xm530/majestic-xm530.mk
include $(BR2_EXTERNAL_XIONGMAI_PATH)/package/mbedtls-openipc/mbedtls-openipc.mk
include $(BR2_EXTERNAL_XIONGMAI_PATH)/package/node-exporter/node-exporter.mk
include $(BR2_EXTERNAL_XIONGMAI_PATH)/package/opus-openipc/opus-openipc.mk
include $(BR2_EXTERNAL_XIONGMAI_PATH)/package/uacme-openipc/uacme-openipc.mk
include $(BR2_EXTERNAL_XIONGMAI_PATH)/package/vtund-openipc/vtund-openipc.mk
include $(BR2_EXTERNAL_XIONGMAI_PATH)/package/xiongmai-osdrv-xm510/xiongmai-osdrv-xm510.mk
include $(BR2_EXTERNAL_XIONGMAI_PATH)/package/xiongmai-osdrv-xm530/xiongmai-osdrv-xm530.mk
include $(BR2_EXTERNAL_XIONGMAI_PATH)/package/yaml-cli/yaml-cli.mk