#!/bin/sh

read_subshell_pid() {
	IFS=' ' read -r subshell_pid _ < /proc/self/stat
}

run_cmd_internal() {
	local subshell_pid
	read_subshell_pid
	local run_cmd_prog="${0##*/}[$subshell_pid]"
	local run_cmd_msg="$1"
	local run_cmd_var="$2"
	local run_cmd_fatal="$3"
	shift 3

	local run_cmd_output
	run_cmd_output=$("$@" 2>&1)
	local run_cmd_rc=$?

	if [ "$run_cmd_rc" -ne 0 ]; then
		if [ -n "$run_cmd_msg" ]; then
			logger -p user.err -t "$run_cmd_prog" "$run_cmd_msg"
		fi

		local run_cmd_symbol
		[ -z "$run_cmd_output" ] && run_cmd_symbol="." || run_cmd_symbol=":"
		logger -p user.err -t "$run_cmd_prog" "Command \`$*\` finished with code $run_cmd_rc$run_cmd_symbol"

		if [ -n "$run_cmd_output" ]; then
			printf '%s\n' "$run_cmd_output" |
			while IFS= read -r line; do
				logger -p user.err -t "$run_cmd_prog" "$line"
			done

			echo "$run_cmd_output" >&2
		fi

		if [ "$run_cmd_fatal" = "false" ]; then
			return "$run_cmd_rc"
		fi

		exit "$run_cmd_rc"
	fi

	if [ -n "$run_cmd_var" ]; then
		eval "$run_cmd_var=\"\$run_cmd_output\""
	elif [ -n "$run_cmd_output" ]; then
		echo "$run_cmd_output"
	fi
}

run_cmd_nonfatal() {
	local run_cmd_msg="$1"
	local run_cmd_var="$2"
	shift 2
	run_cmd_internal "$run_cmd_msg" "$run_cmd_var" "false" "$@"
}

run_cmd() {
	local run_cmd_msg="$1"
	local run_cmd_var="$2"
	shift 2
	run_cmd_internal "$run_cmd_msg" "$run_cmd_var" "true" "$@"
}

kill_pid_file() {
	local signal

	if [ "${1:0:1}" = "-" ]; then
		signal="$1"
		shift
	else
		signal=-15
	fi

	[ -f "$1" ] || return 251
	local pid=$(cat "$1" 2>/dev/null)
	[ -n "$pid" ] && [ -d "/proc/$pid" ] || return 252
	[ "$(cat "/proc/$pid/comm" 2>/dev/null)" = "$2" ] || return 253
	run_cmd_nonfatal "" "" kill "$signal" "$pid" &&
		run_cmd_nonfatal "" "" rm -f "$1"
}
