#!/bin/sh
#
# OpenIPC.org | v.20210811
#

echo -e "\n\e[1;31mСlearing the overlayfs partition and rebooting without any questions...\e[0m\n"
#
flash_eraseall -j /dev/$(awk -F ':' '/rootfs_data/ {print $1}' /proc/mtd) && reboot
