#!/bin/sh

. /usr/sbin/common

for name in privkey endpoint alive pubkey allowed address; do
	NAME=$(echo "$name" | tr '[:lower:]' '[:upper:]')
	run_cmd "Failed to read wg_$name U-Boot environment variable" WG_$NAME fw_printenv -n wg_$name
done

WG_SHARKEY=$(fw_printenv -n wg_sharkey 2>/dev/null || true)

run_cmd "Failed to load wireguard module" "" modprobe wireguard
run_cmd "Failed to create wg0 interface" "" ip link add dev wg0 type wireguard

HOST="${WG_ENDPOINT%:*}"

if ! echo "$HOST" | grep -qE '^\[|^((^|\.)(25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9]?[0-9])){4}$'; then
	while ! nslookup "$HOST" >/dev/null 2>&1; do
		sleep 10
	done
fi

{
	echo "#"
	echo "[Interface]"
	echo "PrivateKey = $WG_PRIVKEY"
	echo
	echo "[Peer]"
	echo "Endpoint = $WG_ENDPOINT"
	echo "PersistentKeepalive = $WG_ALIVE"
	echo "PublicKey = $WG_PUBKEY"
	[ -n "$WG_SHARKEY" ] && echo "PresharedKey = $WG_SHARKEY"
	echo "AllowedIPs = $WG_ALLOWED"
	echo "#"
} >/tmp/wireguard.conf

run_cmd "Failed to apply wireguard configuration" "" wg setconf wg0 /tmp/wireguard.conf

run_cmd "" "" false ip address add dev wg0 "$WG_ADDRESS"
run_cmd "" "" false ip link set up dev wg0

for i in $(echo "$WG_ALLOWED" | tr ',' ' '); do
	run_cmd "" "" false ip -4 route add "$i" dev wg0
done
