#!/bin/sh

run_cmd() {
	local prog="${0##*/}"
	local msg="$1"
	local var="$2"
	shift 2

	local fatal

	if [ "$var" = "--non-fatal" ]; then
		fatal="false"
		var=""
	else
		fatal="true"
	fi

	local output
	output=$("$@" 2>&1)
	local rc=$?

	if [ "$rc" -ne 0 ]; then
		if [ -n "$msg" ]; then
			logger -p user.err -t "$prog[$$]" "$msg"
		elif [ -z "$output" ]; then
			logger -p user.err -t "$prog[$$]" "Command \`$*\` finished with code $rc."
		else
			logger -p user.err -t "$prog[$$]" "Command \`$*\` finished with code $rc:"

			printf '%s\n' "$output" |
			while IFS= read -r line; do
				logger -p user.err -t "$prog[$$]" "$line"
			done
		fi

		if [ -n "$output" ]; then
			echo "$output" >&2
		fi

		if [ "$fatal" = "true" ]; then
			exit "$rc"
		fi	
	fi

	if [ -n "$var" ]; then
		eval "$var=\"\$output\""
	elif [ -n "$output" ]; then
		echo "$output"
	fi
}

run_cmd "Failed to read wg_privkey U-Boot environment variable" WG_PRIVKEY fw_printenv -n wg_privkey
run_cmd "Failed to read wg_endpoint U-Boot environment variable" WG_ENDPOINT fw_printenv -n wg_endpoint
run_cmd "Failed to read wg_alive U-Boot environment variable" WG_ALIVE fw_printenv -n wg_alive
run_cmd "Failed to read wg_pubkey U-Boot environment variable" WG_PUBKEY fw_printenv -n wg_pubkey
run_cmd "Failed to read wg_allowed U-Boot environment variable" WG_ALLOWED fw_printenv -n wg_allowed
run_cmd "Failed to read wg_address U-Boot environment variable" WG_ADDRESS fw_printenv -n wg_address

WG_SHARKEY=$(fw_printenv -n wg_sharkey 2>/dev/null || true)

run_cmd "Failed to load wireguard module" "" modprobe wireguard
run_cmd "Failed to create wg0 interface" "" ip link add dev wg0 type wireguard

HOST="${WG_ENDPOINT%:*}"

if ! echo "$HOST" | grep -qE '^\[|^((^|\.)(25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9]?[0-9])){4}$'; then
	while ! nslookup "$HOST" >/dev/null 2>&1; do
		sleep 10
	done
fi

(
	echo "#"
	echo "[Interface]"
	echo "PrivateKey = $WG_PRIVKEY"
	echo
	echo "[Peer]"
	echo "Endpoint = $WG_ENDPOINT"
	echo "PersistentKeepalive = $WG_ALIVE"
	echo "PublicKey = $WG_PUBKEY"
	[ -n "$WG_SHARKEY" ] && echo "PresharedKey = $WG_SHARKEY"
	echo "AllowedIPs = $WG_ALLOWED"
	echo "#"
) >>/tmp/wireguard.conf

run_cmd "Failed to apply wireguard configuration" "" wg setconf wg0 /tmp/wireguard.conf

run_cmd "" --non-fatal ip address add dev wg0 "$WG_ADDRESS"
run_cmd "" --non-fatal ip link set up dev wg0

for i in $(echo "$WG_ALLOWED" | tr ',' ' '); do
	run_cmd "" --non-fatal ip -4 route add "$i" dev wg0
done
