#!/bin/sh

DAEMON="majestic"
PIDFILE="/var/run/$DAEMON.pid"

DAEMON_ARGS=""

# shellcheck source=/dev/null
[ -r "/etc/default/$DAEMON" ] && . "/etc/default/$DAEMON"

# The daemon does not create a pidfile, and use "-m" to instruct start-stop-daemon to create one.
start() {
	logger -s -p daemon.info -t sigmastar "Check MAC for Sigmastar devices"
	if [ "$(fw_printenv -n ethaddr)" = "D0:22:12:88:88:88" ]; then
		logger -s -p daemon.info -t sigmastar "The eth0 interface has a lousy MAC, let's try to change it.."
	else
		logger -s -p daemon.info -t sigmastar "The eth0 interface has a correct MAC - $(fw_printenv -n ethaddr)"
	fi
	#
	logger -s -p daemon.info -t sigmastar "Loading of kernel modules and initialization of the video system has started"
	export TZ=$(cat /etc/TZ)
	load_sigmastar -i
	#
	printf 'Starting %s: ' "$DAEMON"
	# shellcheck disable=SC2086 # we need the word splitting
	start-stop-daemon -b -m -S -q -p "$PIDFILE" -x "/usr/bin/$DAEMON" \
		-- $DAEMON_ARGS
	status=$?
	if [ "$status" -eq 0 ]; then
		echo "OK"
	else
		echo "FAIL"
	fi
	return "$status"
}

stop() {
	printf 'Stopping %s: ' "$DAEMON"
	start-stop-daemon -K -q -p "$PIDFILE"
	status=$?
	if [ "$status" -eq 0 ]; then
		rm -f "$PIDFILE"
		echo "OK"
	else
		echo "FAIL"
	fi
	return "$status"
}

restart() {
	stop
	sleep 1
	start
}

case "$1" in
	start|stop|restart)
		"$1";;
	reload)
		# Restart, since there is no true "reload" feature.
		restart;;
	*)
		echo "Usage: $0 {start|stop|restart|reload}"
		exit 1
esac
