#!/bin/sh

KMOD_PATH=/lib/modules/4.4.94/ingenic

echo 1 >/proc/sys/vm/overcommit_memory

check_return() {
    if [ $? -ne 0 ]; then
        echo err: $1
        echo exit
        exit
    fi
}

lsmod | grep "sinfo" >/dev/null
if [ $? -ne 0 ]; then
    insmod ${KMOD_PATH/%\//}/sinfo.ko
    check_return "insmod sinfo"
fi
echo 1 >/proc/jz/sinfo/info
check_return "start sinfo"

if fw_printenv -n sensor >/dev/null; then
    export SENSOR=$(fw_printenv -n sensor)
    logger -s -p daemon.info -t ingenic "Get data from environment and set SENSOR as ${SENSOR}"
else
    SENSOR_INFO=$(cat /proc/jz/sinfo/info)
    check_return "get sensor type"
    SENSOR=${SENSOR_INFO#*:}
    if [ "sensor not found" = "$SENSOR" ]; then
        unset SENSOR
        fw_setenv sensor
    else
        logger -s -p daemon.info -t ingenic "Get data from sinfo and set SENSOR as ${SENSOR}"
        fw_setenv sensor $SENSOR && logger -s -p daemon.info -t ingenic "Write detected ${SENSOR} to U-Boot ENV"
    fi
fi

case ${SENSOR} in
"imx307")
    AVPU_PARAM="clk_name='mpll' avpu_clk=550000000"
    ISP_PARAM="clk_name='mpll' isp_clk=367000000 isp_memopt=2"
    SENSOR_PARAM=""
    ;;
"imx335")
    AVPU_PARAM="clk_name='vpll' avpu_clk=654000000"
    ISP_PARAM="clk_name='mpll' isp_clk=367000000 isp_memopt=2"
    SENSOR_PARAM=""
    ;;
"imx415")
    AVPU_PARAM="clk_name='vpll' avpu_clk=654000000"
    ISP_PARAM="isp_clk=350000000"
    SENSOR_PARAM=""
    ;;
*)
    AVPU_PARAM="clk_name='vpll' avpu_clk=654000000"
    ISP_PARAM="isp_clk=350000000"
    SENSOR_PARAM=""
    break
    ;;
esac

echo --------------------
echo "AVPU_PARAM: ${AVPU_PARAM}"
echo "ISP_PARAM: ${ISP_PARAM}"
echo "SENSOR: ${SENSOR}"
echo "SENSOR_PARAM: ${SENSOR_PARAM}"
echo --------------------

lsmod | grep "avpu" >/dev/null
if [ $? -ne 0 ]; then
    insmod ${KMOD_PATH/%\//}/avpu.ko ${AVPU_PARAM}
    check_return "insmod avpu"
fi

lsmod | grep "tx_isp" >/dev/null
if [ $? -ne 0 ]; then
    insmod ${KMOD_PATH/%\//}/tx-isp-t40.ko ${ISP_PARAM}
    check_return "insmod isp drv"
fi

lsmod | grep "audio" >/dev/null
if [ $? -ne 0 ]; then
    insmod ${KMOD_PATH/%\//}/audio.ko
    check_return "insmod audio"
fi

lsmod | grep ${SENSOR} >/dev/null
if [ $? -ne 0 ]; then
    insmod ${KMOD_PATH/%\//}/sensor_${SENSOR}_t40.ko ${SENSOR_PARAM}
    check_return "insmod sensor drv"
fi
#
# Need for claim gpio
insmod ${KMOD_PATH/%\//}/gpio.ko
echo $(yaml-cli -i /etc/majestic.yaml -g .nightMode.irCutPin1) >/proc/jz/claim/gpio
echo $(yaml-cli -i /etc/majestic.yaml -g .nightMode.irCutPin2) >/proc/jz/claim/gpio
# echo $(yaml-cli -i /etc/majestic.yaml -g .nightMode.irSensorPin) >/proc/jz/claim/gpio
#
