#!/bin/sh

KMOD_PATH=/lib/modules/$(uname -r)/ingenic
SOC=$(ipcinfo -f || fw_printenv -n soc)
vendor=$(ipcinfo -v)

if [ ! -f /usr/sbin/sensor_cli ]; then
	ln -s /usr/sbin/extutils /usr/sbin/sensor_cli
fi

echo 1 >/proc/sys/vm/overcommit_memory

log_vendor() {
	logger -s -p daemon.info -t ${vendor} "$1"
}

check_return() {
	if [ $? -ne 0 ]; then
		echo err: $1
		echo exit
		exit
	fi
}

lsmod | grep "sinfo" >/dev/null
if [ $? -ne 0 ]; then
	modprobe sinfo
	check_return "insmod sinfo"
fi

if fw_printenv -n sensor >/dev/null; then
	export SENSOR=$(fw_printenv -n sensor)
	log_vendor "Get data from environment and set SENSOR as ${SENSOR}"
else
	echo 1 >/proc/jz/sinfo/info
	check_return "start sinfo"
	SENSOR_INFO=$(cat /proc/jz/sinfo/info)
	check_return "get sensor type"
	SENSOR=${SENSOR_INFO#*:}
	if [ "sensor not found" = "$SENSOR" ]; then
		unset SENSOR
		fw_setenv sensor
	else
		log_vendor "Get data from sinfo and set SENSOR as ${SENSOR}"
		fw_setenv sensor $SENSOR && log_vendor "Write detected ${SENSOR} to U-Boot ENV"
	fi
fi

case ${SENSOR} in
"imx307")
	AVPU_PARAM="clk_name=mpll avpu_clk=550000000"
	ISP_PARAM="clk_name=mpll isp_clk=367000000 isp_memopt=2"
	SENSOR_PARAM=""
	;;
"imx335")
	AVPU_PARAM="clk_name=vpll avpu_clk=654000000"
	ISP_PARAM="clk_name=mpll isp_clk=367000000 isp_memopt=2"
	SENSOR_PARAM=""
	;;
"imx415")
	AVPU_PARAM="clk_name=vpll avpu_clk=654000000"
	ISP_PARAM="isp_clk=350000000"
	SENSOR_PARAM=""
	;;
*)
	AVPU_PARAM="clk_name=vpll avpu_clk=654000000"
	ISP_PARAM="isp_clk=350000000"
	SENSOR_PARAM=""
	break
	;;
esac

echo --------------------
echo "AVPU_PARAM: ${AVPU_PARAM}"
echo "ISP_PARAM: ${ISP_PARAM}"
echo "SENSOR: ${SENSOR}"
echo "SENSOR_PARAM: ${SENSOR_PARAM}"
echo --------------------

lsmod | grep "avpu" >/dev/null
if [ $? -ne 0 ]; then
	modprobe avpu ${AVPU_PARAM}
	check_return "insmod avpu"
fi

lsmod | grep "tx_isp" >/dev/null
if [ $? -ne 0 ]; then
	modprobe tx-isp-${SOC} ${ISP_PARAM}
	check_return "insmod isp drv"
fi

lsmod | grep ${SENSOR} >/dev/null
if [ $? -ne 0 ]; then
	modprobe sensor_${SENSOR}_${SOC} ${SENSOR_PARAM}
	check_return "insmod sensor drv"
fi

lsmod | grep "audio" >/dev/null
if [ $? -ne 0 ]; then
	modprobe audio spk_gpio=-1
	check_return "insmod audio"
fi

lsmod | grep "gpio" >/dev/null
if [ $? -ne 0 ]; then
	modprobe gpio
	check_return "insmod gpio"
fi

if [ ! -z "$(lsmod | grep "gpio")" ]; then
	GPIOS=".nightMode.irCutPin1 .nightMode.irCutPin2 .nightMode.irSensorPin .nightMode.backlightPin .audio.speakerPin"
	for GPIO in $(echo ${GPIOS})
	do
		G=$(cli -g ${GPIO})
		[ ! -z "${G}" ] && echo ${G} > /proc/gpio_claim/gpio
	done
fi
