#!/bin/sh
#
# OpenIPC.org | 2023.05.01
#

PATH_MODULE=/lib/modules/4.9.84/sigmastar
PATH_FIRMWARE=/etc/sensors/venc_fw/chagall.bin

# Sensor
SENSOR=$(fw_printenv -n sensor)

# Watchdog
watchdog -t 10 /dev/watchdog

insert_ko() {
  insmod ${PATH_MODULE}/mhal.ko
  insmod ${PATH_MODULE}/mi_common.ko
  insmod ${PATH_MODULE}/mi_sys.ko cmdQBufSize=768 logBufSize=256
  insmod ${PATH_MODULE}/mi_rgn.ko
  insmod ${PATH_MODULE}/mi_ldc.ko
  insmod ${PATH_MODULE}/mi_ai.ko
  insmod ${PATH_MODULE}/mi_ao.ko
  insmod ${PATH_MODULE}/mi_mipitx.ko
  insmod ${PATH_MODULE}/mi_sensor.ko
  insmod ${PATH_MODULE}/mi_shadow.ko
  insmod ${PATH_MODULE}/mi_divp.ko
  insmod ${PATH_MODULE}/mi_vif.ko
  insmod ${PATH_MODULE}/mi_vpe.ko
  insmod ${PATH_MODULE}/mi_venc.ko fw_path=${PATH_FIRMWARE}
  insmod ${PATH_MODULE}/sensor_${SENSOR}_mipi.ko chmap=1

  major=$(awk '$2=="mi_poll" {print $1}' /proc/devices)
  mknod /dev/mi_poll c $major 0

  echo isproot /etc/sensors/iqfile > /dev/ispmid
  mdev -s
}

if [ -z ${SENSOR} ]; then
  echo -e "\n\e[1;31mThe sensor parameter is MISSING\e[0m\n" | logger -s -t OpenIPC
  echo -e "\n\e[1;33mUsage: fw_setenv sensor [SENSOR]\e[0m\n" | logger -s -t OpenIPC
  exit 1
else
  echo -e "\n\e[1;32mThe sensor is assigned - ${SENSOR}\e[0m\n" | logger -s -t OpenIPC
fi

if [ ! -e /dev/mi_poll ]; then
  insert_ko
fi

exit 0
