#!/bin/sh
hw=$(ipcinfo -c)
fw=$(grep "BUILD_OPTION" "/etc/os-release" | cut -d= -f2)

echo "Chipset = ${hw}" | logger -s -t RubyFPV
echo "Firmware = ${fw}" | logger -s -t RubyFPV

case "$1" in
	start)
		if ! [ -f /etc/system.ok ]; then
			tweaksys ${hw}
		fi
		echo "Starting Ruby..." | logger -s -t RubyFPV
		ruby_start
		;;

	stop)
		echo "Stopping Ruby..." | logger -s -t RubyFPV
		ruby_stop
		;;

	*)
		echo "Usage: $0 {start|stop}"
		exit 1
		;;
esac
