#!/bin/sh
SOC=$(fw_printenv -n soc)

# SSC338Q CamHi
if [ "$SOC" == "ssc338q" ]; then
	modprobe 8733bu
fi

# HI3516EV300 CamHi
if [ "$SOC" == "hi3516ev300" ]; then
	devmem 0x100C0080 32 0x530
	gpio clear 7
	gpio unexport 7
	modprobe mt7601usta
fi

# T21 BJS
if [ "$SOC" == "t21" ]; then
	gpio clear 50
	gpio unexport 50
	modprobe 8188fu
fi
