include $(BR2_EXTERNAL_GOKE_PATH)/linux/linux-ext-goke_patcher.mk
include $(BR2_EXTERNAL_GOKE_PATH)/package/goke_patcher/goke_patcher.mk
include $(BR2_EXTERNAL_GOKE_PATH)/package/aura-httpd/aura-httpd.mk
include $(BR2_EXTERNAL_GOKE_PATH)/package/ax-agent/ax-agent.mk
include $(BR2_EXTERNAL_GOKE_PATH)/package/baresip-openipc/baresip-openipc.mk
include $(BR2_EXTERNAL_GOKE_PATH)/package/dropbear-openipc/dropbear-openipc.mk
include $(BR2_EXTERNAL_GOKE_PATH)/package/fdk-aac-openipc/fdk-aac-openipc.mk
include $(BR2_EXTERNAL_GOKE_PATH)/package/ffmpeg-openipc/ffmpeg-openipc.mk
include $(BR2_EXTERNAL_GOKE_PATH)/package/fwprintenv-openipc/fwprintenv-openipc.mk
include $(BR2_EXTERNAL_GOKE_PATH)/package/goke-osdrv-gk710x/goke-osdrv-gk710x.mk
include $(BR2_EXTERNAL_GOKE_PATH)/package/goke-osdrv-gk7205v200/goke-osdrv-gk7205v200.mk
include $(BR2_EXTERNAL_GOKE_PATH)/package/hisilicon-opensdk/hisilicon-opensdk.mk
include $(BR2_EXTERNAL_GOKE_PATH)/package/i2c-telemetry/i2c-telemetry.mk
include $(BR2_EXTERNAL_GOKE_PATH)/package/ipctool/ipctool.mk
include $(BR2_EXTERNAL_GOKE_PATH)/package/json-c-openipc/json-c-openipc.mk
include $(BR2_EXTERNAL_GOKE_PATH)/package/lame-openipc/lame-openipc.mk
include $(BR2_EXTERNAL_GOKE_PATH)/package/libcurl-openipc/libcurl-openipc.mk
include $(BR2_EXTERNAL_GOKE_PATH)/package/libevent-openipc/libevent-openipc.mk
include $(BR2_EXTERNAL_GOKE_PATH)/package/libhv-openipc/libhv-openipc.mk
include $(BR2_EXTERNAL_GOKE_PATH)/package/libogg-openipc/libogg-openipc.mk
include $(BR2_EXTERNAL_GOKE_PATH)/package/libre-openipc/libre-openipc.mk
include $(BR2_EXTERNAL_GOKE_PATH)/package/librem-openipc/librem-openipc.mk
include $(BR2_EXTERNAL_GOKE_PATH)/package/libsrt-openipc/libsrt-openipc.mk
include $(BR2_EXTERNAL_GOKE_PATH)/package/libwebsockets-openipc/libwebsockets-openipc.mk
include $(BR2_EXTERNAL_GOKE_PATH)/package/linux-firmware-openipc/linux-firmware-openipc.mk
include $(BR2_EXTERNAL_GOKE_PATH)/package/majestic/majestic.mk
include $(BR2_EXTERNAL_GOKE_PATH)/package/majestic-fonts/majestic-fonts.mk
include $(BR2_EXTERNAL_GOKE_PATH)/package/mavlink-router/mavlink-router.mk
include $(BR2_EXTERNAL_GOKE_PATH)/package/mbedtls-openipc/mbedtls-openipc.mk
include $(BR2_EXTERNAL_GOKE_PATH)/package/microbe-web/microbe-web.mk
include $(BR2_EXTERNAL_GOKE_PATH)/package/motors/motors.mk
include $(BR2_EXTERNAL_GOKE_PATH)/package/mt7601u-ap-openipc/mt7601u-ap-openipc.mk
include $(BR2_EXTERNAL_GOKE_PATH)/package/node-exporter/node-exporter.mk
include $(BR2_EXTERNAL_GOKE_PATH)/package/opus-openipc/opus-openipc.mk
include $(BR2_EXTERNAL_GOKE_PATH)/package/rtl8188fu-openipc/rtl8188fu-openipc.mk
include $(BR2_EXTERNAL_GOKE_PATH)/package/rtl8812au-openipc/rtl8812au-openipc.mk
include $(BR2_EXTERNAL_GOKE_PATH)/package/uacme-openipc/uacme-openipc.mk
include $(BR2_EXTERNAL_GOKE_PATH)/package/vtund-openipc/vtund-openipc.mk
include $(BR2_EXTERNAL_GOKE_PATH)/package/wifibroadcast/wifibroadcast.mk
include $(BR2_EXTERNAL_GOKE_PATH)/package/yaml-cli/yaml-cli.mk
include $(BR2_EXTERNAL_GOKE_PATH)/package/xmdp/xmdp.mk
include $(BR2_EXTERNAL_GOKE_PATH)/package/zerotier-one/zerotier-one.mk
