include $(BR2_EXTERNAL_INGENIC_PATH)/linux/linux-ext-ingenic_patcher.mk
include $(BR2_EXTERNAL_INGENIC_PATH)/package/ingenic-osdrv-t20/ingenic-osdrv-t20.mk
include $(BR2_EXTERNAL_INGENIC_PATH)/package/ingenic-osdrv-t21/ingenic-osdrv-t21.mk
include $(BR2_EXTERNAL_INGENIC_PATH)/package/ingenic-osdrv-t31/ingenic-osdrv-t31.mk
include $(BR2_EXTERNAL_INGENIC_PATH)/package/ingenic_patcher/ingenic_patcher.mk
include $(BR2_EXTERNAL_INGENIC_PATH)/package/aura-httpd/aura-httpd.mk
include $(BR2_EXTERNAL_INGENIC_PATH)/package/ax-agent/ax-agent.mk
include $(BR2_EXTERNAL_INGENIC_PATH)/package/dropbear-openipc/dropbear-openipc.mk
include $(BR2_EXTERNAL_INGENIC_PATH)/package/fdk-aac-openipc/fdk-aac-openipc.mk
include $(BR2_EXTERNAL_INGENIC_PATH)/package/ffmpeg-openipc/ffmpeg-openipc.mk
include $(BR2_EXTERNAL_INGENIC_PATH)/package/fwprintenv-openipc/fwprintenv-openipc.mk
include $(BR2_EXTERNAL_INGENIC_PATH)/package/i2c-telemetry/i2c-telemetry.mk
include $(BR2_EXTERNAL_INGENIC_PATH)/package/ipctool/ipctool.mk
include $(BR2_EXTERNAL_INGENIC_PATH)/package/json-c-openipc/json-c-openipc.mk
include $(BR2_EXTERNAL_INGENIC_PATH)/package/lame-openipc/lame-openipc.mk
include $(BR2_EXTERNAL_INGENIC_PATH)/package/libcurl-openipc/libcurl-openipc.mk
include $(BR2_EXTERNAL_INGENIC_PATH)/package/libevent-openipc/libevent-openipc.mk
include $(BR2_EXTERNAL_INGENIC_PATH)/package/libhv-openipc/libhv-openipc.mk
include $(BR2_EXTERNAL_INGENIC_PATH)/package/libogg-openipc/libogg-openipc.mk
include $(BR2_EXTERNAL_INGENIC_PATH)/package/libsrt-openipc/libsrt-openipc.mk
include $(BR2_EXTERNAL_INGENIC_PATH)/package/libwebsockets-openipc/libwebsockets-openipc.mk
include $(BR2_EXTERNAL_INGENIC_PATH)/package/linux-firmware-openipc/linux-firmware-openipc.mk
include $(BR2_EXTERNAL_INGENIC_PATH)/package/majestic/majestic.mk
include $(BR2_EXTERNAL_INGENIC_PATH)/package/majestic-fonts/majestic-fonts.mk
include $(BR2_EXTERNAL_INGENIC_PATH)/package/mbedtls-openipc/mbedtls-openipc.mk
include $(BR2_EXTERNAL_INGENIC_PATH)/package/microbe-web/microbe-web.mk
include $(BR2_EXTERNAL_INGENIC_PATH)/package/microsnander/microsnander.mk
include $(BR2_EXTERNAL_INGENIC_PATH)/package/motors/motors.mk
include $(BR2_EXTERNAL_INGENIC_PATH)/package/node-exporter/node-exporter.mk
include $(BR2_EXTERNAL_INGENIC_PATH)/package/opus-openipc/opus-openipc.mk
include $(BR2_EXTERNAL_INGENIC_PATH)/package/rtl8188fu-openipc/rtl8188fu-openipc.mk
include $(BR2_EXTERNAL_INGENIC_PATH)/package/uacme-openipc/uacme-openipc.mk
include $(BR2_EXTERNAL_INGENIC_PATH)/package/vtund-openipc/vtund-openipc.mk
include $(BR2_EXTERNAL_INGENIC_PATH)/package/xmdp/xmdp.mk
include $(BR2_EXTERNAL_INGENIC_PATH)/package/yaml-cli/yaml-cli.mk
