include $(BR2_EXTERNAL_INGENIC_PATH)/linux/linux-ext-ingenic_patcher.mk
include $(BR2_EXTERNAL_INGENIC_PATH)/package/ingenic_patcher/ingenic_patcher.mk
include $(BR2_EXTERNAL_INGENIC_PATH)/package/aura-httpd/aura-httpd.mk
include $(BR2_EXTERNAL_INGENIC_PATH)/package/fwprintenv-openipc/fwprintenv-openipc.mk
include $(BR2_EXTERNAL_INGENIC_PATH)/package/ipctool/ipctool.mk
include $(BR2_EXTERNAL_INGENIC_PATH)/package/lame-openipc/lame-openipc.mk
include $(BR2_EXTERNAL_INGENIC_PATH)/package/libevent-openipc/libevent-openipc.mk
include $(BR2_EXTERNAL_INGENIC_PATH)/package/libhv-openipc/libhv-openipc.mk
include $(BR2_EXTERNAL_INGENIC_PATH)/package/libogg-openipc/libogg-openipc.mk
include $(BR2_EXTERNAL_INGENIC_PATH)/package/libsrt-openipc/libsrt-openipc.mk
include $(BR2_EXTERNAL_INGENIC_PATH)/package/majestic/majestic.mk
include $(BR2_EXTERNAL_INGENIC_PATH)/package/mbedtls-openipc/mbedtls-openipc.mk
include $(BR2_EXTERNAL_INGENIC_PATH)/package/node-exporter/node-exporter.mk
include $(BR2_EXTERNAL_INGENIC_PATH)/package/opus-openipc/opus-openipc.mk
include $(BR2_EXTERNAL_INGENIC_PATH)/package/vtund-openipc/vtund-openipc.mk
include $(BR2_EXTERNAL_INGENIC_PATH)/package/yaml-cli/yaml-cli.mk