#!/bin/sh

set_gpio() {
	echo $1 > /sys/class/gpio/export
	echo out > /sys/class/gpio/gpio$1/direction
	echo $2 > /sys/class/gpio/gpio$1/value
	sleep 1
}

set_mmc() {
	mmc=/sys/devices/platform/jzmmc_v1.2.$1/present
	if [ "$(cat $mmc)" = "N" ]; then
		echo "INSERT" > $mmc
	fi
}

# T31 ATBM603X mmc0
if [ "$1" = "atbm603x-t31-mmc0" ]; then
	# PB10 wifi mmc1, pull-down -> high-impedance
	devmem 0x10011128 32 0x400
	# Set wifi mmc1 clk drive capability to 8mA
	devmem 0x10011134 32 0x20000
	set_mmc 0

	cp /usr/share/atbm603x_conf/atbm_txpwer_dcxo_cfg.txt /tmp
	cp /usr/share/atbm603x_conf/set_rate_power.txt /tmp
	modprobe atbm603x_wifi_sdi0 atbm_printk_mask=0
	exit 0
fi

# T31 ATBM603X mmc1
if [ "$1" = "atbm603x-t31-mmc1" ]; then
	# Copied from stock firmware
	devmem 0x10011110 32 0x6e094800
	set_mmc 1

	cp /usr/share/atbm603x_conf/atbm_txpwer_dcxo_cfg.txt /tmp
	cp /usr/share/atbm603x_conf/set_rate_power.txt /tmp
	modprobe atbm603x_wifi_sdi1 atbm_printk_mask=0
	exit 0
fi

# T31 Wyze V3 / AtomCam 2 ATBM603x
if [ "$1" = "atbm603x-t31-wyze-v3" ]; then
	set_gpio 57 1
	set_mmc 1

	cp /usr/share/atbm603x_conf/atbm_txpwer_dcxo_cfg.txt /tmp
	cp /usr/share/atbm603x_conf/set_rate_power.txt /tmp
	modprobe atbm603x_wifi_sdi1 atbm_printk_mask=0
	exit 0
fi

# T31 Wyze V3 RTL8189FTV
if [ "$1" = "rtl8189ftv-t31-wyze-v3" ]; then
	set_gpio 57 1
	set_mmc 1
	modprobe 8189fs rtw_power_mgnt=0 rtw_enusbss=0
	exit 0
fi

# T31 Wyze DB3 RTL8189FTV
if [ "$1" = "rtl8189ftv-t31-wyze-db3" ]; then
	set_mmc 1
	modprobe 8189fs rtw_power_mgnt=0 rtw_enusbss=0
	exit 0
fi

# T20 Wyze V2 RTL8189FTV
if [ "$1" = "rtl8189ftv-t20-wyze-v2" ]; then
	set_mmc 1
	modprobe 8189fs rtw_power_mgnt=0 rtw_enusbss=0
	exit 0
fi

# T20 Wyze PanV1 RTL8189ES
if [ "$1" = "rtl8189ftv-t20-wyze-pan-v1" ]; then
	set_mmc 1
	modprobe 8189es rtw_power_mgnt=0 rtw_enusbss=0
	exit 0
fi

exit 1
