#!/bin/sh
dev=$(fw_printenv -n wlandev)
mac=$(fw_printenv -n wlanmac)
net=$(fw_printenv -n netaddr_fallback)
eth=$(fw_printenv -n ethaddr)

set_wireless() {
	path=/etc/wireless
	if $path/usb "$dev" || $path/sdio "$dev"; then
		[ -n "$mac" ] && ip link set dev wlan0 address "$mac"
		ifup wlan0
	elif $path/modem "$dev"; then
		ifup usb0
		ifup eth1
	fi
	[ -e /sys/class/net/eth0 ] && ifconfig eth0 "${net:-192.168.2.10}" hw ether "${eth:-00:00:23:34:45:66}" up
}

is_nfs_root() {
    grep -qw 'root=/dev/nfs' /proc/cmdline
}

start() {
	echo "Starting network..."
	if [ -n "$dev" ]; then
		ifup lo
		set_wireless
	else
		if is_nfs_root; then
			echo "nfs-root: NFS root detected, leaving eth0/lo as configured by kernel"
		else
			ifup lo
			ifup eth0
		fi
	fi
}

stop() {
	echo "Stopping network..."
	ifdown lo
	ifdown -f wlan0
	ifdown -f usb0
	ifdown -f eth1
	if is_nfs_root; then
		echo "NFS root detected, leaving eth0 up during shutdown"
	else
		ifdown -f eth0
	fi
}

case "$1" in
	start|stop)
		$1
		;;

	restart|reload)
		stop
		start
		;;

	*)
		echo "Usage: $0 {start|stop|restart|reload}"
		exit 1
		;;
esac
