#!/bin/sh

DAEMON="dropbear"
PIDFILE="/var/run/$DAEMON.pid"
DAEMON_ARGS="-B -k -p 22 -K 300"

start() {
	if fw_printenv >/dev/null 2>&1; then
		if ! fw_printenv ssh_key; then
			echo "<6>nfs-root: Generating SSH key and saving to uboot env" > /dev/kmsg
			tmp="$(mktemp -u /tmp/dropbearkey.XXXXXX)" || exit 1
			trap 'rm -f "$tmp"' EXIT

			dropbearkey -t ed25519 -f "$tmp" >/dev/null 2>&1 || exit 1
			SSH_KEY=$(cat "$tmp" | base64 -w 0)
			fw_setenv ssh_key $SSH_KEY
		fi
		echo "<6>nfs-root: Loading SSH key from uboot env" > /dev/kmsg
		fw_printenv -n ssh_key 2>/dev/null | base64 -d > /etc/dropbear/dropbear_ed25519_host_key
	else
		echo "<6>nfs-root: fw_setenv inaccessible, SSH key will not be saved"
		DAEMON_ARGS="${DAEMON_ARGS} -R"
	fi
	
	echo -n "Starting $DAEMON: "
	umask 077
	start-stop-daemon -S -q -p "$PIDFILE" -x "$DAEMON" -- $DAEMON_ARGS
	if [ $? -eq 0 ]; then
		echo "OK"
	else
		echo "FAIL"
	fi
}

stop() {
	echo -n "Stopping $DAEMON: "
	start-stop-daemon -K -q -p "$PIDFILE"
	if [ $? -eq 0 ]; then
		rm -f "$PIDFILE"
		echo "OK"
	else
		echo "FAIL"
	fi
}

case "$1" in
	start|stop)
		$1
		;;

	restart|reload)
		stop
		sleep 1
		start
		;;

	*)
		echo "Usage: $0 {start|stop|restart|reload}"
		exit 1
		;;
esac
