#!/bin/sh
#
# Start Net TMP....
#


start() {
    ifconfig eth0 up 172.19.32.200 netmask 255.255.255.0
    route add default gw 172.19.32.1
}

case "$1" in
    start)
	start
	;;
  *)
	echo "Usage: $0 {start}"
	exit 1
esac

exit $?
