#!/bin/sh

WIFI=XM711

if [ "$WIFI" = "XM711" ]; then
	insmod /usr/lib/modules/dwc_common_port_lib.ko
	insmod /usr/lib/modules/dwc_otg.ko
	insmod /usr/lib/modules/wifi_pdn.ko value=96
	insmod /usr/lib/modules/compat.ko
	insmod /usr/lib/modules/cfg80211.ko
	insmod /usr/lib/modules/xm711.ko
fi

