include $(BR2_EXTERNAL_SIGMASTAR_PATH)/linux/linux-ext-sigmastar_patcher.mk
include $(BR2_EXTERNAL_SIGMASTAR_PATH)/package/sigmastar_patcher/sigmastar_patcher.mk
include $(BR2_EXTERNAL_SIGMASTAR_PATH)/package/aura-httpd/aura-httpd.mk
include $(BR2_EXTERNAL_SIGMASTAR_PATH)/package/fwprintenv-openipc/fwprintenv-openipc.mk
include $(BR2_EXTERNAL_SIGMASTAR_PATH)/package/gdbserver-lite/gdbserver-lite.mk
include $(BR2_EXTERNAL_SIGMASTAR_PATH)/package/ipctool/ipctool.mk
include $(BR2_EXTERNAL_SIGMASTAR_PATH)/package/libevent-openipc/libevent-openipc.mk
include $(BR2_EXTERNAL_SIGMASTAR_PATH)/package/libhv/libhv.mk
include $(BR2_EXTERNAL_SIGMASTAR_PATH)/package/libogg-openipc/libogg-openipc.mk
include $(BR2_EXTERNAL_SIGMASTAR_PATH)/package/libsrt/libsrt.mk
include $(BR2_EXTERNAL_SIGMASTAR_PATH)/package/majestic-ssc335/majestic-ssc335.mk
include $(BR2_EXTERNAL_SIGMASTAR_PATH)/package/mbedtls-openipc/mbedtls-openipc.mk
include $(BR2_EXTERNAL_SIGMASTAR_PATH)/package/node-exporter/node-exporter.mk
include $(BR2_EXTERNAL_SIGMASTAR_PATH)/package/opus-openipc/opus-openipc.mk
include $(BR2_EXTERNAL_SIGMASTAR_PATH)/package/sigmastar-osdrv-ssc335/sigmastar-osdrv-ssc335.mk
include $(BR2_EXTERNAL_SIGMASTAR_PATH)/package/vtund-openipc/vtund-openipc.mk
include $(BR2_EXTERNAL_SIGMASTAR_PATH)/package/yaml-cli/yaml-cli.mk