name: cache
on:
  workflow_dispatch:

env:
  REMOVE: linux* gcc glibc aws* majestic mini

jobs:
  download:
    name: Download
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Prepare download
        id: cache
        uses: actions/cache@v3
        with:
          path: /tmp/download
          key: buildroot-cache

      - name: Download files
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          DIR=/tmp/download
          export BR2_DL_DIR=${DIR}
          LIST=$(find br-ext-chip-*/configs -type f -name *_defconfig)
          for CONFIG in ${LIST}; do
            echo --- ${CONFIG}
            make BOARD=${CONFIG} br-source
          done
          cd ${DIR}
          rm -rf ${REMOVE}
