name: toolchain
on:
  workflow_dispatch:

env:
  TAG_NAME: toolchain

jobs:
  toolchain:
    name: Toolchain
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          # Sigmastar
          - {"platform": "ssc325"}
          - {"platform": "ssc335"}
          - {"platform": "ssc377"}
          - {"platform": "ssc338q"}

          # Hisilicon
          - {"platform": "hi3516av100"}
          - {"platform": "hi3516cv100"}
          - {"platform": "hi3516cv200"}
          - {"platform": "hi3516cv300"}
          - {"platform": "hi3516cv500"}
          - {"platform": "hi3516ev200"}
          - {"platform": "hi3519v101"}
          - {"platform": "hi3536cv100"}
          - {"platform": "hi3536dv100"}

          # Goke
          - {"platform": "gk7102"}
          - {"platform": "gk7205v200"}

          # Ingenic
          - {"platform": "t20"}
          - {"platform": "t21"}
          - {"platform": "t31"}
          - {"platform": "t40"}

          # Allwinner
          - {"platform": "v851s"}

          # Fullhan
          - {"platform": "fh8852v100"}
          - {"platform": "fh8852v200"}

          # Grainmedia
          - {"platform": "gm8136"}

          # Novatek
          - {"platform": "nt98562"}

          # Rockchip
          - {"platform": "rv1126"}

          # Xiongmai
          - {"platform": "xm510"}
          - {"platform": "xm530"}

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Build toolchain
        run: |
          CONFIG=$(find br-ext-chip-* -name ${{matrix.platform}}_lite_defconfig)
          GCC=$(make BOARD=${CONFIG} toolname).tgz
          URL=https://github.com/${GITHUB_REPOSITORY}/releases/download/${TAG_NAME}/${GCC}
          echo ${URL}
          if ! wget -q --spider ${URL}; then
            make BOARD=${CONFIG} toolchain
            SDK=$(find output/images -name *_sdk-buildroot.tar.gz)
            mv ${SDK} ${GCC}
            echo GCC=${GCC} >> ${GITHUB_ENV}
          fi

      - name: Upload toolchain
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{env.TAG_NAME}}
          make_latest: false
          files: ${{env.GCC}}
