name: uboot
on:
  workflow_dispatch:

jobs:
  toolchain:
    name: Uboot
    runs-on: ubuntu-latest
    steps:
      - name: Prepare
        run: |
          sudo apt-get update
          sudo apt-get install gcc-arm-linux-gnueabi gcc-mipsel-linux-gnu u-boot-tools lzop gnutls-dev lzma-alone

      - name: Allwinner
        run: |
          git clone https://github.com/openipc/u-boot-allwinner --depth 1
          cd u-boot-allwinner
          bash build.sh

      - name: Ingenic
        run: |
          git clone https://github.com/openipc/u-boot-ingenic --depth 1
          cd u-boot-ingenic
          bash build.sh

      - name: Sigmastar
        run: |
          git clone https://github.com/openipc/u-boot-sigmastar --depth 1
          cd u-boot-sigmastar
          bash build.sh

      - name: Upload
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          files: |
            u-boot-*/output/*-nor.bin
            u-boot-*/output/*-nand.bin
